### ISSUE TITLE
Error creating / grabbing account for: "USERNAME"

### ISSUE THREAD

**Issue by MrCamping** [iConomy/Core#105] opened 2011-06-22 00:14 UTC
SInce I upgraded to iConomy 5.0,1 account are not created for new players.
Players that already had an account before the update still have it, but no new accounts are created.
I get this message in Console when a new player logs in.

[INFO] [iConomy] Error creating / grabbing account for: "USERNAME"

I have iConomy 5.0.1 using MySql and CB860

Lots of people reported this bug in forums too.

**Comment by Moochie** [comment] 2011-06-22 09:11
iConomy is working fine for me on bukkit 818 but once I go up to 860 I get the same thing and it does make sense if it doesn't work because iConomy 5.0.1 is only tested up to 845.

I am not sure if anyone has posted all this but this is what I get.  The extra stuff may help solve this issue, I don't know.

09:02:45 [INFO] [iConomy] Error creating / grabbing account for: Moochiez
09:02:50 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'mone
y' in plugin iConomy v5.01
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:12
8)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:2
87)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.
java:712)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:678)

```
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:671)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:32)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:75)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:399)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:309)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
```

Caused by: java.lang.NullPointerException
        at com.iConomy.iConomy.format(iConomy.java:396)
        at com.iConomy.entity.Players.showBalance(Players.java:451)
        at com.iConomy.entity.Players.onPlayerCommand(Players.java:1554)
        at com.iConomy.iConomy.onCommand(iConomy.java:218)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:35)
        ... 12 more

**Comment by nijikokun** [comment] 2011-06-26 16:47
It is fixed in iConomy6

**Closed as completed** 2011-06-26 16:51 UTC
Labels: Feature

**Comment by dumptruckman** [comment] 2011-07-05 15:43
Is there any way to release a fix for this sooner?  I've had to create a web page that users can go to to register an account but i've realized recently that when they create new towns through Towny, it cannot set up an account for the town.  Getting the webpage to make that is a little bit trickier, I'm afraid.
